spring:
  application:
    name: demo-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

kafka:
  bootstrap-servers: localhost:9092
  topic:

swagger:
  title: Demo API
  version: 1.0.0
  description: API для управления задачами, пользователями и уведомлениями